#!/bin/bash

# The follwoing will attempt to install all needed packages to run Hyprland
# This is a quick and dirty script there are no error checking
# This script is meant to run on a clean fresh system
#
# Below is a list of the packages that would be installed
# TODO: ADD THE FUCKING LIST

BPurple='\033[1;35m'
BRed='\033[1;31m'
NC='\033[0m'
#### Check for yay ####
ISYAY=/sbin/yay
if [ -f "$ISYAY" ]; then
  printf "${BPurple}yay was located, moving on.${NC}\n"
else
  printf "${BRed}yay was not located.${NC}\n"

  read -n1 -rep "Would you like to install yay to continue this install? y/n: " YAYS
  if [[ $YAYS == "Y" || $YAYS == y ]]; then
    printf "${BPurple}Creating ~/git/yay and installing yay.${NC}"
    mkdir ~/git
    cd ~/git
    git clone https://aur.archlinux.org/yay.git
    cd yay
    makepkg -sic
  else
    printf "${BRed}\nUnable to continue install without yay.${NC}\n"
    exit
  fi
fi

### Install all of the above pacakges ####
read -n1 -rep 'Would you like to install the packages? y/n: ' INST
if [[ $INST == "Y" || $INST == "y" ]]; then
  yay -Syu
  yay -S - <./packages.txt
  yay -Yc

  # enable tlp and bluetooth
  sudo systemctl enable --now tlp.service
  sudo systemctl enable --now bluetooth.service
  sudo systemctl enable --now tlp.service

  # Clean out other conflicting portals
  yay -R --noconfirm xdg-desktop-portal-gnome xdg-desktop-portal-gnome

  # Install live-server for nvim
  pnpm add -g live-server
  pnpm fund
fi

### Set zsh as shell ###
read -n1 -rep 'Would you like to set your shell to ZSH? y,n: ' ZSH
if [[ $ZSH == "Y" || $ZSH == "y" ]]; then
  printf "${BPurple}\nChanging shell to ZSH:\n${NC}"
  sudo chsh -s $(whch zsh)
fi

### Copy Config Files ###
read -n1 -rep 'Would you like to copy config files and start? y/n: ' CFG
if [[ $CFG == "Y" || $CFG == "y" ]]; then
  printf "${BPurple}Copying config files...${NC}\n"

  sudo cp -R ./config/* ~/.config/

  ### Root Changes: ###

  # tlp:
  sudo cp ./root/tlp/tlp.conf /etc/tlp.conf

  # grub:
  sudo cp -r ./root/grub/catppuccin-mocha-custom/ /usr/share/grub/themes/
  sudo cp ./root/grub/grub /etc/default/grub

  sudo grub-mkconfig -o /boot/grub/grub.cfg

  # reflector:
  sudo cp ./root/reflector/reflector.conf /etc/xdg/reflector/reflector.conf
  sudo systemctl enable --now reflector.service reflector.timer
  sudo systemctl start reflector.service reflector.timer

  ### Userspace/.config Changes: ###

  # zsh:
  sudo cp ./config/zsh/themes/heapbytes.zsh-theme ~/.oh-my-zsh/themes
  sudo cp ./config/zsh/.zshrc ~/.zshrc

  sudo cp -r ./config/zsh/plugins/zsh-lsd ~/.oh-my-zsh/plugins/

  # tpm:
  printf "${BPurple}\nInstalling Tmux TPM${NC}"
  git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
  sudo cp ./config/tmux/.tmux.conf ~/.tmux.conf

  # gtk theme:
  sudo cp -r ./root/gtk/theme/Dracula/ /usr/share/themes/
  sudo cp -r ./root/gtk/icons/Dracula/ /usr/share/icons/

  gsettings set org.gnome.desktop.interface gtk-theme "Dracula"
  gsettings set org.gnome.desktop.wm.preferences theme "Dracula"

  gsettings set org.gnome.desktop.interface icon-theme "Dracula"

  # gtk/swaync/cursors (AKA THEMING):
  sudo cp ./config/gtk/.gtkrc-2.0.mime ~/.gtkrc-2.0.mime

  sudo mkdir -p ~/.config/gtk-3.0/
  sudo cp ./config/gtk/settings.ini ~/.config/gtk-3.0/settings.ini

  sudo mkdir -p ~/.config/swaync
  sudo cp ./config/swaync/style.css ~/.config/swaync/style.css
  sudo cp ./config/swaync/config.json ~/.config/swaync/config.json

  gsettings set org.gnome.desktop.interface cursor-theme macOS

  sudo mkdir -p ~/.local/share/icons/default
  sudo ln --symbolic /usr/share/icons/macOS ~/.local/share/icons/default/

  sudo mkdir -p ~/.config/xfce4/xfconf/xfce-perchannel-xml/
  sudo cp ./config/xfce4/xsettings.xml ~/.config/xfce4/xfconf/xfce-perchannel-xml/xsettings.xml

  # Set some files as executable
  sudo chmod +x ~/.config/hypr/scripts/xdg-portal-hyprland
  sudo chmod +x ~/.config/waybar/scripts/weather.sh

  # Default settings:
  gsettings set org.cinnamon.desktop.default-applications.terminal exec kitty

  # greetd:
  printf "${BPurple}\nCopying and enabling Greetd${NC}"
  sudo cp ./root/greetd/config.toml /etc/greetd/config.toml
  sudo systemctl enable --now greetd.service

  # CHOWNING everythin to make it all work:
  sudo chown -R $USER:$USER ~/

fi

printf "\n${BPurple}Script has completed!${NC}\n"
