decoration {
    # See https://wiki.hyprland.org/Configuring/Variables/ for more

    rounding = 10

    blur {
        enabled = false
        size = 2
        passes = 1
    }

    inactive_opacity = 0.9
}

input {
    kb_layout = us
    kb_variant =
    kb_model =
    kb_options =
    kb_rules =

    follow_mouse = 1

    touchpad {
        natural_scroll = no
        disable_while_typing = no
    }

    sensitivity = 0 # -1.0 - 1.0, 0 means no modification.
}

dwindle {
    # See https://wiki.hyprland.org/Configuring/Dwindle-Layout/ for more
    pseudotile = yes # master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
    preserve_split = yes # you probably want this
}

animations {
    enabled = yes
}

misc {
  disable_hyprland_logo = true
  vfr = true
}
